apiVersion: v1
kind: Service
metadata:
  name: storefront
  namespace: ${KUBERNETES_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: storefront
  ports:
    - name: storefront
      protocol: TCP
      port: 8080
    - name: storefront-mgt
      protocol: TCP
      port: 9080
      